baseURL = "http://v2.climact.de/"
languageCode = "en-us"
title = "Climact v2"
theme = "book"

# Here to be able to use <img> tags.
# TODO: Really necessary?
[markup.goldmark.renderer]
unsafe= true

[params]
BookLogo = 'static/logo.png'
